# Generated by Django 2.2.4 on 2019-10-06 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(max_length=10)),
                ('l_type', models.CharField(max_length=50)),
                ('l_date', models.DateField(default=datetime.date.today)),
                ('l_time', models.TimeField(auto_now_add=True)),
                ('l_reason', models.CharField(max_length=200)),
                ('l_days', models.IntegerField(max_length=10)),
                ('l_status', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tbl_leave',
            },
        ),
        migrations.CreateModel(
            name='tbl_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(max_length=10)),
                ('emp_img', models.CharField(max_length=200)),
                ('emp_dob', models.DateField(default=datetime.date.today)),
                ('emp_email', models.CharField(max_length=50)),
                ('emp_phone', models.IntegerField(max_length=10)),
                ('emp_address', models.CharField(max_length=200)),
                ('emp_type', models.CharField(max_length=50)),
                ('emp_discriptin', models.CharField(max_length=200)),
                ('emp_last_edit', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'tbl_profile',
            },
        ),
    ]
