# Generated by Django 2.2.4 on 2019-10-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0002_auto_20191006_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_leave',
            name='emp_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_leave',
            name='l_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_profile',
            name='emp_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_profile',
            name='emp_img',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='tbl_profile',
            name='emp_phone',
            field=models.IntegerField(null=True),
        ),
    ]
