# Generated by Django 2.2.4 on 2019-10-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0004_auto_20191010_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_leave',
            name='l_year',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
