# Generated by Django 2.2.4 on 2019-10-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0005_tbl_leave_l_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_leave',
            name='l_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_leave',
            name='l_to',
            field=models.DateField(null=True),
        ),
    ]
