# Generated by Django 2.2.4 on 2019-10-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0006_auto_20191011_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_leave',
            name='l_r_reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
