# Generated by Django 2.2.4 on 2019-10-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0007_tbl_leave_l_r_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_leave',
            name='emp_name',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
