# Generated by Django 2.2.4 on 2019-10-22 07:01

from django.db import migrations, models
import leave_management_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0008_tbl_leave_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_profile',
            name='emp_img',
            field=models.ImageField(upload_to=leave_management_system.models.imgAuth),
        ),
    ]
