# Generated by Django 2.2.4 on 2019-10-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0009_auto_20191022_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_profile',
            name='emp_img',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='tbl_profile',
            name='emp_phone',
            field=models.CharField(default='NULL', max_length=15),
            preserve_default=False,
        ),
    ]
