# Generated by Django 2.2.4 on 2019-10-23 06:02

from django.db import migrations, models
import leave_management_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0010_auto_20191022_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_profile',
            name='emp_auth',
            field=models.CharField(default='Pending', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_profile',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_profile',
            name='emp_img',
            field=models.ImageField(upload_to=leave_management_system.models.imgAuth),
        ),
    ]
