# Generated by Django 2.2.4 on 2019-11-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0011_auto_20191023_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_profile',
            name='emp_manager',
            field=models.CharField(default='NULL', max_length=50),
            preserve_default=False,
        ),
    ]
